from enum import IntFlag

import comtypes.gen._CE3F726E_D1D3_44FE_B995_FF1DB3B48B2B_0_1_3 as __wrapper_module__
from typing import TYPE_CHECKING
if TYPE_CHECKING:
	from ._CE3F726E_D1D3_44FE_B995_FF1DB3B48B2B_0_1_3 import (
        IA2_EVENT_HYPERTEXT_LINK_SELECTED, IAccessibleTable2,
        IA2_ROLE_CHECK_MENU_ITEM, IA2_ROLE_CANVAS, IAccessibleRelation,
        IA2_ROLE_TEXT_FRAME, IA2_TEXT_BOUNDARY_WORD, IAccessibleText2,
        IA2_ROLE_INPUT_METHOD_WINDOW,
        IA2_EVENT_HYPERLINK_END_INDEX_CHANGED, IA2_ROLE_HEADER,
        IA2_STATE_DEFUNCT, IA2_ROLE_SHAPE, IA2_ROLE_IMAGE_MAP,
        IA2_EVENT_HYPERLINK_NUMBER_OF_ANCHORS_CHANGED,
        IA2_EVENT_DOCUMENT_ATTRIBUTE_CHANGED, IA2_SCROLL_TYPE_ANYWHERE,
        IA2_ROLE_INTERNAL_FRAME, IA2_STATE_PINNED, IA2_TEXT_BOUNDARY_ALL,
        IA2_STATE_EDITABLE, IA2_ROLE_COLOR_CHOOSER, IAccessibleTable,
        IAccessibleImage, STRING, IA2_ROLE_HEADING, IA2_TEXT_OFFSET_CARET,
        IA2_ROLE_LAYERED_PANE, IA2_ROLE_MARK, IAccessibleTableCell,
        IA2_EVENT_TABLE_ROW_HEADER_CHANGED,
        IA2_EVENT_TABLE_CAPTION_CHANGED, IA2_SCROLL_TYPE_BOTTOM_EDGE,
        IA2_STATE_REQUIRED, IA2_STATE_MULTI_LINE,
        IA2_TABLE_MODEL_CHANGE_DELETE, IA2_ROLE_EDITBAR,
        IA2_COORDTYPE_PARENT_RELATIVE, IA2_TEXT_BOUNDARY_PARAGRAPH,
        IA2_EVENT_TABLE_COLUMN_HEADER_CHANGED, IA2_TEXT_BOUNDARY_SENTENCE,
        IA2_ROLE_ICON, IA2_ROLE_TERMINAL, IAccessibleAction,
        IA2_ROLE_REDUNDANT_OBJECT, IA2_SCROLL_TYPE_BOTTOM_RIGHT, Library,
        IA2_SCROLL_TYPE_TOP_EDGE, IA2_ROLE_COMPLEMENTARY_CONTENT,
        IA2_ROLE_FONT_CHOOSER, IA2_STATE_OPAQUE, VARIANT,
        IA2_ROLE_UNKNOWN, IA2_EVENT_TABLE_ROW_DESCRIPTION_CHANGED,
        IA2_EVENT_TEXT_INSERTED, IA2_EVENT_TEXT_CHANGED, IA2_ROLE_FRAME,
        IA2_ROLE_SPLIT_PANE, IA2_EVENT_OBJECT_ATTRIBUTE_CHANGED,
        IA2_EVENT_ACTIVE_DECENDENT_CHANGED, IA2TextSelection, WSTRING,
        IA2_TABLE_MODEL_CHANGE_UPDATE, IA2_EVENT_ACTION_CHANGED,
        IA2_ROLE_DIRECTORY_PANE, IA2_EVENT_VISIBLE_DATA_CHANGED,
        IA2_ROLE_SCROLL_PANE, IA2_EVENT_HYPERTEXT_NLINKS_CHANGED,
        IA2_STATE_ARMED, IA2_ROLE_PARAGRAPH, IA2_ROLE_TEAR_OFF_MENU,
        IA2_ROLE_ROOT_PANE, IAccessible2_2, IA2_STATE_CHECKABLE,
        IA2_ROLE_ENDNOTE, IA2_STATE_INVALID_ENTRY, IA2_ROLE_LABEL,
        IA2_EVENT_TEXT_CARET_MOVED, IAccessibleText,
        IA2_TEXT_BOUNDARY_CHAR, IA2_STATE_MODAL,
        IA2_EVENT_TABLE_MODEL_CHANGED, COMMETHOD,
        IA2_EVENT_TEXT_COLUMN_CHANGED, IA2_ROLE_SECTION,
        IA2_EVENT_DOCUMENT_LOAD_COMPLETE, IA2_ROLE_DATE_EDITOR,
        IAccessibleHypertext, IAccessibleHypertext2,
        IA2_TABLE_MODEL_CHANGE_INSERT, _lcid, IA2_SCROLL_TYPE_RIGHT_EDGE,
        IA2_COORDTYPE_SCREEN_RELATIVE, IA2_ROLE_GLASS_PANE,
        IA2_EVENT_DOCUMENT_CONTENT_CHANGED, IA2_STATE_HORIZONTAL,
        IA2_ROLE_VIEW_PORT, IAccessibleDocument, IA2TableModelChange,
        IA2_ROLE_CAPTION, IA2_ROLE_CONTENT_INSERTION,
        IAccessibleHyperlink, IA2_TEXT_OFFSET_LENGTH,
        IA2_ROLE_CONTENT_DELETION, IAccessibleComponent, IA2TextSegment,
        IAccessible2, IA2_EVENT_HYPERTEXT_LINK_ACTIVATED,
        IA2_EVENT_ACTIVE_DESCENDANT_CHANGED, IA2_ROLE_DESKTOP_PANE,
        IA2_EVENT_TABLE_COLUMN_DESCRIPTION_CHANGED,
        IA2_EVENT_HYPERTEXT_CHANGED, IAccessibleApplication, IA2Locale,
        IA2_EVENT_ROLE_CHANGED, IA2_EVENT_DOCUMENT_RELOAD,
        IA2_STATE_SUPPORTS_AUTOCOMPLETION, IA2_ROLE_LANDMARK,
        IAccessibleValue, IA2_ROLE_FILE_CHOOSER, IA2_EVENT_TEXT_UPDATED,
        IA2_EVENT_HYPERLINK_SELECTED_LINK_CHANGED, IA2_ROLE_NOTE,
        IA2_ROLE_RULER, IA2_ROLE_BLOCK_QUOTE, IA2_STATE_SINGLE_LINE,
        IA2_EVENT_TEXT_REMOVED, IA2_SCROLL_TYPE_TOP_LEFT,
        IA2_ROLE_RADIO_MENU_ITEM, IA2_ROLE_EMBEDDED_OBJECT,
        IA2_ROLE_OPTION_PANE, IA2_ROLE_DESKTOP_ICON, IUnknown,
        IA2_TEXT_BOUNDARY_LINE, IA2_STATE_STALE,
        IA2_STATE_MANAGES_DESCENDANTS, GUID, typelib_path,
        IA2_ROLE_LEVEL_BAR, IA2_ROLE_FOOTER, IA2_STATE_ICONIFIED,
        IA2_EVENT_HYPERLINK_START_INDEX_CHANGED, IA2_STATE_TRANSIENT,
        IA2_STATE_VERTICAL, IA2_EVENT_TEXT_SELECTION_CHANGED,
        IA2_EVENT_TEXT_ATTRIBUTE_CHANGED, IA2_SCROLL_TYPE_LEFT_EDGE,
        IA2_EVENT_SECTION_CHANGED, IA2_EVENT_PAGE_CHANGED,
        IA2_ROLE_COMMENT, IA2_ROLE_FORM, IA2_STATE_SELECTABLE_TEXT,
        IA2_ROLE_PAGE, IAccessibleEditableText,
        IAccessibleTextSelectionContainer, BSTR, IA2_STATE_ACTIVE,
        IA2_EVENT_TABLE_SUMMARY_CHANGED, IA2_ROLE_TOGGLE_BUTTON,
        IA2_ROLE_FOOTNOTE, IA2_ROLE_SUGGESTION,
        IA2_EVENT_DOCUMENT_LOAD_STOPPED, HRESULT
	)
else:
	from comtypes.gen._CE3F726E_D1D3_44FE_B995_FF1DB3B48B2B_0_1_3 import (
        IA2_EVENT_HYPERTEXT_LINK_SELECTED, IAccessibleTable2,
        IA2_ROLE_CHECK_MENU_ITEM, IA2_ROLE_CANVAS, IAccessibleRelation,
        IA2_ROLE_TEXT_FRAME, IA2_TEXT_BOUNDARY_WORD, IAccessibleText2,
        IA2_ROLE_INPUT_METHOD_WINDOW,
        IA2_EVENT_HYPERLINK_END_INDEX_CHANGED, IA2_ROLE_HEADER,
        IA2_STATE_DEFUNCT, IA2_ROLE_SHAPE, IA2_ROLE_IMAGE_MAP,
        IA2_EVENT_HYPERLINK_NUMBER_OF_ANCHORS_CHANGED,
        IA2_EVENT_DOCUMENT_ATTRIBUTE_CHANGED, IA2_SCROLL_TYPE_ANYWHERE,
        IA2_ROLE_INTERNAL_FRAME, IA2_STATE_PINNED, IA2_TEXT_BOUNDARY_ALL,
        IA2_STATE_EDITABLE, IA2_ROLE_COLOR_CHOOSER, IAccessibleTable,
        IAccessibleImage, STRING, IA2_ROLE_HEADING, IA2_TEXT_OFFSET_CARET,
        IA2_ROLE_LAYERED_PANE, IA2_ROLE_MARK, IAccessibleTableCell,
        IA2_EVENT_TABLE_ROW_HEADER_CHANGED,
        IA2_EVENT_TABLE_CAPTION_CHANGED, IA2_SCROLL_TYPE_BOTTOM_EDGE,
        IA2_STATE_REQUIRED, IA2_STATE_MULTI_LINE,
        IA2_TABLE_MODEL_CHANGE_DELETE, IA2_ROLE_EDITBAR,
        IA2_COORDTYPE_PARENT_RELATIVE, IA2_TEXT_BOUNDARY_PARAGRAPH,
        IA2_EVENT_TABLE_COLUMN_HEADER_CHANGED, IA2_TEXT_BOUNDARY_SENTENCE,
        IA2_ROLE_ICON, IA2_ROLE_TERMINAL, IAccessibleAction,
        IA2_ROLE_REDUNDANT_OBJECT, IA2_SCROLL_TYPE_BOTTOM_RIGHT, Library,
        IA2_SCROLL_TYPE_TOP_EDGE, IA2_ROLE_COMPLEMENTARY_CONTENT,
        IA2_ROLE_FONT_CHOOSER, IA2_STATE_OPAQUE, VARIANT,
        IA2_ROLE_UNKNOWN, IA2_EVENT_TABLE_ROW_DESCRIPTION_CHANGED,
        IA2_EVENT_TEXT_INSERTED, IA2_EVENT_TEXT_CHANGED, IA2_ROLE_FRAME,
        IA2_ROLE_SPLIT_PANE, IA2_EVENT_OBJECT_ATTRIBUTE_CHANGED,
        IA2_EVENT_ACTIVE_DECENDENT_CHANGED, IA2TextSelection, WSTRING,
        IA2_TABLE_MODEL_CHANGE_UPDATE, IA2_EVENT_ACTION_CHANGED,
        IA2_ROLE_DIRECTORY_PANE, IA2_EVENT_VISIBLE_DATA_CHANGED,
        IA2_ROLE_SCROLL_PANE, IA2_EVENT_HYPERTEXT_NLINKS_CHANGED,
        IA2_STATE_ARMED, IA2_ROLE_PARAGRAPH, IA2_ROLE_TEAR_OFF_MENU,
        IA2_ROLE_ROOT_PANE, IAccessible2_2, IA2_STATE_CHECKABLE,
        IA2_ROLE_ENDNOTE, IA2_STATE_INVALID_ENTRY, IA2_ROLE_LABEL,
        IA2_EVENT_TEXT_CARET_MOVED, IAccessibleText,
        IA2_TEXT_BOUNDARY_CHAR, IA2_STATE_MODAL,
        IA2_EVENT_TABLE_MODEL_CHANGED, COMMETHOD,
        IA2_EVENT_TEXT_COLUMN_CHANGED, IA2_ROLE_SECTION,
        IA2_EVENT_DOCUMENT_LOAD_COMPLETE, IA2_ROLE_DATE_EDITOR,
        IAccessibleHypertext, IAccessibleHypertext2,
        IA2_TABLE_MODEL_CHANGE_INSERT, _lcid, IA2_SCROLL_TYPE_RIGHT_EDGE,
        IA2_COORDTYPE_SCREEN_RELATIVE, IA2_ROLE_GLASS_PANE,
        IA2_EVENT_DOCUMENT_CONTENT_CHANGED, IA2_STATE_HORIZONTAL,
        IA2_ROLE_VIEW_PORT, IAccessibleDocument, IA2TableModelChange,
        IA2_ROLE_CAPTION, IA2_ROLE_CONTENT_INSERTION,
        IAccessibleHyperlink, IA2_TEXT_OFFSET_LENGTH,
        IA2_ROLE_CONTENT_DELETION, IAccessibleComponent, IA2TextSegment,
        IAccessible2, IA2_EVENT_HYPERTEXT_LINK_ACTIVATED,
        IA2_EVENT_ACTIVE_DESCENDANT_CHANGED, IA2_ROLE_DESKTOP_PANE,
        IA2_EVENT_TABLE_COLUMN_DESCRIPTION_CHANGED,
        IA2_EVENT_HYPERTEXT_CHANGED, IAccessibleApplication, IA2Locale,
        IA2_EVENT_ROLE_CHANGED, IA2_EVENT_DOCUMENT_RELOAD,
        IA2_STATE_SUPPORTS_AUTOCOMPLETION, IA2_ROLE_LANDMARK,
        IAccessibleValue, IA2_ROLE_FILE_CHOOSER, IA2_EVENT_TEXT_UPDATED,
        IA2_EVENT_HYPERLINK_SELECTED_LINK_CHANGED, IA2_ROLE_NOTE,
        IA2_ROLE_RULER, IA2_ROLE_BLOCK_QUOTE, IA2_STATE_SINGLE_LINE,
        IA2_EVENT_TEXT_REMOVED, IA2_SCROLL_TYPE_TOP_LEFT,
        IA2_ROLE_RADIO_MENU_ITEM, IA2_ROLE_EMBEDDED_OBJECT,
        IA2_ROLE_OPTION_PANE, IA2_ROLE_DESKTOP_ICON, IUnknown,
        IA2_TEXT_BOUNDARY_LINE, IA2_STATE_STALE,
        IA2_STATE_MANAGES_DESCENDANTS, GUID, typelib_path,
        IA2_ROLE_LEVEL_BAR, IA2_ROLE_FOOTER, IA2_STATE_ICONIFIED,
        IA2_EVENT_HYPERLINK_START_INDEX_CHANGED, IA2_STATE_TRANSIENT,
        IA2_STATE_VERTICAL, IA2_EVENT_TEXT_SELECTION_CHANGED,
        IA2_EVENT_TEXT_ATTRIBUTE_CHANGED, IA2_SCROLL_TYPE_LEFT_EDGE,
        IA2_EVENT_SECTION_CHANGED, IA2_EVENT_PAGE_CHANGED,
        IA2_ROLE_COMMENT, IA2_ROLE_FORM, IA2_STATE_SELECTABLE_TEXT,
        IA2_ROLE_PAGE, IAccessibleEditableText,
        IAccessibleTextSelectionContainer, BSTR, IA2_STATE_ACTIVE,
        IA2_EVENT_TABLE_SUMMARY_CHANGED, IA2_ROLE_TOGGLE_BUTTON,
        IA2_ROLE_FOOTNOTE, IA2_ROLE_SUGGESTION,
        IA2_EVENT_DOCUMENT_LOAD_STOPPED, HRESULT
	)


class IA2EventID(IntFlag):
    IA2_EVENT_ACTION_CHANGED = 257
    IA2_EVENT_ACTIVE_DECENDENT_CHANGED = 258
    IA2_EVENT_ACTIVE_DESCENDANT_CHANGED = 258
    IA2_EVENT_DOCUMENT_ATTRIBUTE_CHANGED = 259
    IA2_EVENT_DOCUMENT_CONTENT_CHANGED = 260
    IA2_EVENT_DOCUMENT_LOAD_COMPLETE = 261
    IA2_EVENT_DOCUMENT_LOAD_STOPPED = 262
    IA2_EVENT_DOCUMENT_RELOAD = 263
    IA2_EVENT_HYPERLINK_END_INDEX_CHANGED = 264
    IA2_EVENT_HYPERLINK_NUMBER_OF_ANCHORS_CHANGED = 265
    IA2_EVENT_HYPERLINK_SELECTED_LINK_CHANGED = 266
    IA2_EVENT_HYPERTEXT_LINK_ACTIVATED = 267
    IA2_EVENT_HYPERTEXT_LINK_SELECTED = 268
    IA2_EVENT_HYPERLINK_START_INDEX_CHANGED = 269
    IA2_EVENT_HYPERTEXT_CHANGED = 270
    IA2_EVENT_HYPERTEXT_NLINKS_CHANGED = 271
    IA2_EVENT_OBJECT_ATTRIBUTE_CHANGED = 272
    IA2_EVENT_PAGE_CHANGED = 273
    IA2_EVENT_SECTION_CHANGED = 274
    IA2_EVENT_TABLE_CAPTION_CHANGED = 275
    IA2_EVENT_TABLE_COLUMN_DESCRIPTION_CHANGED = 276
    IA2_EVENT_TABLE_COLUMN_HEADER_CHANGED = 277
    IA2_EVENT_TABLE_MODEL_CHANGED = 278
    IA2_EVENT_TABLE_ROW_DESCRIPTION_CHANGED = 279
    IA2_EVENT_TABLE_ROW_HEADER_CHANGED = 280
    IA2_EVENT_TABLE_SUMMARY_CHANGED = 281
    IA2_EVENT_TEXT_ATTRIBUTE_CHANGED = 282
    IA2_EVENT_TEXT_CARET_MOVED = 283
    IA2_EVENT_TEXT_CHANGED = 284
    IA2_EVENT_TEXT_COLUMN_CHANGED = 285
    IA2_EVENT_TEXT_INSERTED = 286
    IA2_EVENT_TEXT_REMOVED = 287
    IA2_EVENT_TEXT_UPDATED = 288
    IA2_EVENT_TEXT_SELECTION_CHANGED = 289
    IA2_EVENT_VISIBLE_DATA_CHANGED = 290
    IA2_EVENT_ROLE_CHANGED = 291


class IA2ScrollType(IntFlag):
    IA2_SCROLL_TYPE_TOP_LEFT = 0
    IA2_SCROLL_TYPE_BOTTOM_RIGHT = 1
    IA2_SCROLL_TYPE_TOP_EDGE = 2
    IA2_SCROLL_TYPE_BOTTOM_EDGE = 3
    IA2_SCROLL_TYPE_LEFT_EDGE = 4
    IA2_SCROLL_TYPE_RIGHT_EDGE = 5
    IA2_SCROLL_TYPE_ANYWHERE = 6


class IA2CoordinateType(IntFlag):
    IA2_COORDTYPE_SCREEN_RELATIVE = 0
    IA2_COORDTYPE_PARENT_RELATIVE = 1


class IA2Role(IntFlag):
    IA2_ROLE_UNKNOWN = 0
    IA2_ROLE_CANVAS = 1025
    IA2_ROLE_CAPTION = 1026
    IA2_ROLE_CHECK_MENU_ITEM = 1027
    IA2_ROLE_COLOR_CHOOSER = 1028
    IA2_ROLE_DATE_EDITOR = 1029
    IA2_ROLE_DESKTOP_ICON = 1030
    IA2_ROLE_DESKTOP_PANE = 1031
    IA2_ROLE_DIRECTORY_PANE = 1032
    IA2_ROLE_EDITBAR = 1033
    IA2_ROLE_EMBEDDED_OBJECT = 1034
    IA2_ROLE_ENDNOTE = 1035
    IA2_ROLE_FILE_CHOOSER = 1036
    IA2_ROLE_FONT_CHOOSER = 1037
    IA2_ROLE_FOOTER = 1038
    IA2_ROLE_FOOTNOTE = 1039
    IA2_ROLE_FORM = 1040
    IA2_ROLE_FRAME = 1041
    IA2_ROLE_GLASS_PANE = 1042
    IA2_ROLE_HEADER = 1043
    IA2_ROLE_HEADING = 1044
    IA2_ROLE_ICON = 1045
    IA2_ROLE_IMAGE_MAP = 1046
    IA2_ROLE_INPUT_METHOD_WINDOW = 1047
    IA2_ROLE_INTERNAL_FRAME = 1048
    IA2_ROLE_LABEL = 1049
    IA2_ROLE_LAYERED_PANE = 1050
    IA2_ROLE_NOTE = 1051
    IA2_ROLE_OPTION_PANE = 1052
    IA2_ROLE_PAGE = 1053
    IA2_ROLE_PARAGRAPH = 1054
    IA2_ROLE_RADIO_MENU_ITEM = 1055
    IA2_ROLE_REDUNDANT_OBJECT = 1056
    IA2_ROLE_ROOT_PANE = 1057
    IA2_ROLE_RULER = 1058
    IA2_ROLE_SCROLL_PANE = 1059
    IA2_ROLE_SECTION = 1060
    IA2_ROLE_SHAPE = 1061
    IA2_ROLE_SPLIT_PANE = 1062
    IA2_ROLE_TEAR_OFF_MENU = 1063
    IA2_ROLE_TERMINAL = 1064
    IA2_ROLE_TEXT_FRAME = 1065
    IA2_ROLE_TOGGLE_BUTTON = 1066
    IA2_ROLE_VIEW_PORT = 1067
    IA2_ROLE_COMPLEMENTARY_CONTENT = 1068
    IA2_ROLE_LANDMARK = 1069
    IA2_ROLE_LEVEL_BAR = 1070
    IA2_ROLE_CONTENT_DELETION = 1071
    IA2_ROLE_CONTENT_INSERTION = 1072
    IA2_ROLE_BLOCK_QUOTE = 1073
    IA2_ROLE_MARK = 1074
    IA2_ROLE_SUGGESTION = 1075
    IA2_ROLE_COMMENT = 1076


class IA2TableModelChangeType(IntFlag):
    IA2_TABLE_MODEL_CHANGE_INSERT = 0
    IA2_TABLE_MODEL_CHANGE_DELETE = 1
    IA2_TABLE_MODEL_CHANGE_UPDATE = 2


class IA2TextBoundaryType(IntFlag):
    IA2_TEXT_BOUNDARY_CHAR = 0
    IA2_TEXT_BOUNDARY_WORD = 1
    IA2_TEXT_BOUNDARY_SENTENCE = 2
    IA2_TEXT_BOUNDARY_PARAGRAPH = 3
    IA2_TEXT_BOUNDARY_LINE = 4
    IA2_TEXT_BOUNDARY_ALL = 5


class IA2States(IntFlag):
    IA2_STATE_ACTIVE = 1
    IA2_STATE_ARMED = 2
    IA2_STATE_DEFUNCT = 4
    IA2_STATE_EDITABLE = 8
    IA2_STATE_HORIZONTAL = 16
    IA2_STATE_ICONIFIED = 32
    IA2_STATE_INVALID_ENTRY = 64
    IA2_STATE_MANAGES_DESCENDANTS = 128
    IA2_STATE_MODAL = 256
    IA2_STATE_MULTI_LINE = 512
    IA2_STATE_OPAQUE = 1024
    IA2_STATE_REQUIRED = 2048
    IA2_STATE_SELECTABLE_TEXT = 4096
    IA2_STATE_SINGLE_LINE = 8192
    IA2_STATE_STALE = 16384
    IA2_STATE_SUPPORTS_AUTOCOMPLETION = 32768
    IA2_STATE_TRANSIENT = 65536
    IA2_STATE_VERTICAL = 131072
    IA2_STATE_CHECKABLE = 262144
    IA2_STATE_PINNED = 524288


class IA2TextSpecialOffsets(IntFlag):
    IA2_TEXT_OFFSET_LENGTH = -1
    IA2_TEXT_OFFSET_CARET = -2


__all__ = [
    'IA2_EVENT_HYPERTEXT_LINK_SELECTED', 'IAccessibleTable2',
    'IA2_ROLE_CHECK_MENU_ITEM', 'IA2_ROLE_CANVAS',
    'IAccessibleRelation', 'IA2_ROLE_TEXT_FRAME',
    'IA2_TEXT_BOUNDARY_WORD', 'IAccessibleText2',
    'IA2_ROLE_INPUT_METHOD_WINDOW',
    'IA2_EVENT_HYPERLINK_END_INDEX_CHANGED', 'IA2_ROLE_HEADER',
    'IA2_STATE_DEFUNCT', 'IA2_ROLE_SHAPE', 'IA2_ROLE_IMAGE_MAP',
    'IA2_EVENT_HYPERLINK_NUMBER_OF_ANCHORS_CHANGED',
    'IA2_EVENT_DOCUMENT_ATTRIBUTE_CHANGED',
    'IA2_SCROLL_TYPE_ANYWHERE', 'IA2_ROLE_INTERNAL_FRAME',
    'IA2_STATE_PINNED', 'IA2_TEXT_BOUNDARY_ALL', 'IA2_STATE_EDITABLE',
    'IA2_ROLE_COLOR_CHOOSER', 'IAccessibleTable', 'IAccessibleImage',
    'IA2_ROLE_HEADING', 'IA2_TEXT_OFFSET_CARET',
    'IA2_ROLE_LAYERED_PANE', 'IA2_ROLE_MARK', 'IAccessibleTableCell',
    'IA2_EVENT_TABLE_ROW_HEADER_CHANGED',
    'IA2_EVENT_TABLE_CAPTION_CHANGED', 'IA2_SCROLL_TYPE_BOTTOM_EDGE',
    'IA2_STATE_REQUIRED', 'IA2_STATE_MULTI_LINE', 'IA2ScrollType',
    'IA2_TABLE_MODEL_CHANGE_DELETE', 'IA2_ROLE_EDITBAR',
    'IA2_COORDTYPE_PARENT_RELATIVE', 'IA2_TEXT_BOUNDARY_PARAGRAPH',
    'IA2_EVENT_TABLE_COLUMN_HEADER_CHANGED',
    'IA2_TEXT_BOUNDARY_SENTENCE', 'IA2_ROLE_ICON',
    'IA2_ROLE_TERMINAL', 'IAccessibleAction',
    'IA2_ROLE_REDUNDANT_OBJECT', 'IA2_SCROLL_TYPE_BOTTOM_RIGHT',
    'Library', 'IA2_SCROLL_TYPE_TOP_EDGE',
    'IA2_ROLE_COMPLEMENTARY_CONTENT', 'IA2_ROLE_FONT_CHOOSER',
    'IA2_STATE_OPAQUE', 'IA2_ROLE_UNKNOWN',
    'IA2_EVENT_TABLE_ROW_DESCRIPTION_CHANGED',
    'IA2_EVENT_TEXT_INSERTED', 'IA2_EVENT_TEXT_CHANGED',
    'IA2TextSpecialOffsets', 'IA2_ROLE_FRAME', 'IA2_ROLE_SPLIT_PANE',
    'IA2_EVENT_OBJECT_ATTRIBUTE_CHANGED',
    'IA2_EVENT_ACTIVE_DECENDENT_CHANGED', 'IA2TextSelection',
    'IA2_TABLE_MODEL_CHANGE_UPDATE', 'IA2_EVENT_ACTION_CHANGED',
    'IA2_ROLE_DIRECTORY_PANE', 'IA2_EVENT_VISIBLE_DATA_CHANGED',
    'IA2_ROLE_SCROLL_PANE', 'IA2_EVENT_HYPERTEXT_NLINKS_CHANGED',
    'IA2_STATE_ARMED', 'IA2_ROLE_PARAGRAPH', 'IA2_ROLE_TEAR_OFF_MENU',
    'IA2_ROLE_ROOT_PANE', 'IAccessible2_2', 'IA2_STATE_CHECKABLE',
    'IA2_ROLE_ENDNOTE', 'IA2_STATE_INVALID_ENTRY', 'IA2_ROLE_LABEL',
    'IA2_EVENT_TEXT_CARET_MOVED', 'IAccessibleText',
    'IA2_TEXT_BOUNDARY_CHAR', 'IA2_STATE_MODAL',
    'IA2_EVENT_TABLE_MODEL_CHANGED', 'IA2_EVENT_TEXT_COLUMN_CHANGED',
    'IA2_ROLE_SECTION', 'IA2_EVENT_DOCUMENT_LOAD_COMPLETE',
    'IA2_ROLE_DATE_EDITOR', 'IAccessibleHypertext',
    'IAccessibleHypertext2', 'IA2_TABLE_MODEL_CHANGE_INSERT',
    'IA2States', 'IA2_SCROLL_TYPE_RIGHT_EDGE',
    'IA2_COORDTYPE_SCREEN_RELATIVE', 'IA2_ROLE_GLASS_PANE',
    'IA2_EVENT_DOCUMENT_CONTENT_CHANGED', 'IA2_STATE_HORIZONTAL',
    'IA2_ROLE_VIEW_PORT', 'IAccessibleDocument',
    'IA2TableModelChange', 'IA2_ROLE_CAPTION',
    'IA2_ROLE_CONTENT_INSERTION', 'IAccessibleHyperlink',
    'IA2_TEXT_OFFSET_LENGTH', 'IA2_ROLE_CONTENT_DELETION',
    'IAccessibleComponent', 'IA2TextSegment',
    'IA2TableModelChangeType', 'IAccessible2',
    'IA2_EVENT_HYPERTEXT_LINK_ACTIVATED',
    'IA2_EVENT_ACTIVE_DESCENDANT_CHANGED', 'IA2_ROLE_DESKTOP_PANE',
    'IA2_EVENT_TABLE_COLUMN_DESCRIPTION_CHANGED',
    'IA2_EVENT_HYPERTEXT_CHANGED', 'IAccessibleApplication',
    'IA2Locale', 'IA2_EVENT_ROLE_CHANGED',
    'IA2_EVENT_DOCUMENT_RELOAD', 'IA2_STATE_SUPPORTS_AUTOCOMPLETION',
    'IA2_ROLE_LANDMARK', 'IAccessibleValue', 'IA2TextBoundaryType',
    'IA2CoordinateType', 'IA2_ROLE_FILE_CHOOSER',
    'IA2_EVENT_TEXT_UPDATED',
    'IA2_EVENT_HYPERLINK_SELECTED_LINK_CHANGED', 'IA2_ROLE_NOTE',
    'IA2_ROLE_RULER', 'IA2_ROLE_BLOCK_QUOTE', 'IA2_STATE_SINGLE_LINE',
    'IA2_EVENT_TEXT_REMOVED', 'IA2_SCROLL_TYPE_TOP_LEFT',
    'IA2_ROLE_RADIO_MENU_ITEM', 'IA2_ROLE_EMBEDDED_OBJECT',
    'IA2_ROLE_OPTION_PANE', 'IA2_ROLE_DESKTOP_ICON',
    'IA2_TEXT_BOUNDARY_LINE', 'IA2_STATE_STALE', 'IA2Role',
    'IA2_STATE_MANAGES_DESCENDANTS', 'IA2EventID', 'typelib_path',
    'IA2_ROLE_LEVEL_BAR', 'IA2_ROLE_FOOTER', 'IA2_STATE_ICONIFIED',
    'IA2_EVENT_HYPERLINK_START_INDEX_CHANGED', 'IA2_STATE_TRANSIENT',
    'IA2_STATE_VERTICAL', 'IA2_EVENT_TEXT_SELECTION_CHANGED',
    'IA2_EVENT_TEXT_ATTRIBUTE_CHANGED', 'IA2_SCROLL_TYPE_LEFT_EDGE',
    'IA2_EVENT_SECTION_CHANGED', 'IA2_EVENT_PAGE_CHANGED',
    'IA2_ROLE_COMMENT', 'IA2_ROLE_FORM', 'IA2_STATE_SELECTABLE_TEXT',
    'IA2_ROLE_PAGE', 'IAccessibleEditableText',
    'IAccessibleTextSelectionContainer', 'IA2_STATE_ACTIVE',
    'IA2_EVENT_TABLE_SUMMARY_CHANGED', 'IA2_ROLE_TOGGLE_BUTTON',
    'IA2_ROLE_FOOTNOTE', 'IA2_ROLE_SUGGESTION',
    'IA2_EVENT_DOCUMENT_LOAD_STOPPED'
]

